/**
 * Alert Service
 *
 * Creates, assigns, and dispatches alerts generated by the Risk Engine,
 * Voice AI emergency detection, or manual officer escalation.
 *
 * ADD §9 Alert Center Architecture:
 *   Alert Sources → Alert Created → Assign Officer → Notify Caregiver → Resolution
 */

const prisma = require('../config/prisma');
const { notificationQueue } = require('../queues/queues');

// ── createFromRiskScore ───────────────────────────────────────────────────────

/**
 * Convenience wrapper called by riskEngine.service when score ≥ threshold.
 */
async function createFromRiskScore({ elderlyId, organizationId, score, riskLevel, factors }) {
  const title       = `ผู้สูงอายุมีความเสี่ยง${riskLevel} (คะแนน ${score}/100)`;
  const description = buildRiskDescription(score, riskLevel, factors);

  return createAlert({
    elderlyId,
    organizationId,
    alertType:   'HEALTH',
    severity:    riskLevel,
    title,
    description,
  });
}

// ── createAlert ───────────────────────────────────────────────────────────────

/**
 * Core alert creation.
 *
 * @param {object} opts
 * @param {string}  opts.elderlyId
 * @param {string}  opts.organizationId
 * @param {string}  opts.alertType   — MEDICATION | HEALTH | APPOINTMENT | EMERGENCY | NO_ANSWER
 * @param {string}  opts.severity    — LOW | MEDIUM | HIGH | CRITICAL
 * @param {string}  opts.title
 * @param {string}  [opts.description]
 * @param {string}  [opts.assignedUserId]  — Override auto-assignment
 *
 * @returns {Prisma.Alert}
 */
async function createAlert({ elderlyId, organizationId, alertType, severity, title, description, assignedUserId }) {
  const eid   = BigInt(elderlyId);
  const orgId = BigInt(organizationId);

  // ── 1. Auto-assign officer ─────────────────────────────────────────────────
  let assigneeId = assignedUserId ? BigInt(assignedUserId) : null;

  if (!assigneeId) {
    const officer = await prisma.user.findFirst({
      where:   { organizationId: orgId, role: { in: ['OFFICER', 'NURSE'] }, isActive: true },
      orderBy: { assignedAlerts: { _count: 'asc' } },
      select:  { id: true },
    });
    assigneeId = officer?.id ?? null;
  }

  // ── 2. Create alert row ────────────────────────────────────────────────────
  const alert = await prisma.alert.create({
    data: {
      elderlyId:      eid,
      alertType:      alertType || null,
      severity:       severity  || null,
      title,
      description:    description ?? null,
      status:         'OPEN',
      assignedUserId: assigneeId,
    },
    include: {
      elderly: {
        select: {
          firstName: true,
          lastName:  true,
          phone:     true,
          lineUserId: true,
          organizationId: true,
          caregivers: {
            where:   { isPrimary: true },
            select:  { fullName: true, phone: true, lineUserId: true },
            take:    1,
          },
          emergencyContacts: {
            orderBy: { priorityOrder: 'asc' },
            select:  { contactName: true, phone: true },
            take:    2,
          },
        },
      },
    },
  });

  // ── 3. Build notification targets ─────────────────────────────────────────
  const alertMessage = buildAlertMessage(alert);
  const queueJobs    = [];

  // Notify assigned officer via SMS
  if (assigneeId) {
    const officer = await prisma.user.findUnique({
      where:  { id: assigneeId },
      select: { phone: true, email: true },
    });

    const officerRecipient = officer?.phone;
    if (officerRecipient) {
      const notif = await prisma.notification.create({
        data: {
          elderlyId:      eid,
          alertId:        alert.id,
          channel:        'SMS',
          recipient:      officerRecipient,
          subject:        `alert:${alert.id}:officer`,
          message:        alertMessage,
          deliveryStatus: 'PENDING',
        },
      });

      queueJobs.push({
        name: 'alert-notification',
        data: {
          notificationId: notif.id.toString(),
          elderlyId,
          channel:        'SMS',
          recipient:      officerRecipient,
          subject:        `alert:${alert.id}:officer`,
          message:        alertMessage,
          alertId:        alert.id.toString(),
          organizationId,
        },
      });
    }
  }

  // Notify primary caregiver via LINE (preferred) or SMS
  const caregiver = alert.elderly.caregivers[0];
  if (caregiver) {
    const channel   = caregiver.lineUserId ? 'LINE' : 'SMS';
    const recipient = caregiver.lineUserId || caregiver.phone;

    if (recipient) {
      const careMsg = buildCaregiverMessage(alert, caregiver.fullName);
      const notif = await prisma.notification.create({
        data: {
          elderlyId:      eid,
          alertId:        alert.id,
          channel,
          recipient,
          subject:        `alert:${alert.id}:caregiver`,
          message:        careMsg,
          deliveryStatus: 'PENDING',
        },
      });

      queueJobs.push({
        name: 'alert-notification',
        data: {
          notificationId: notif.id.toString(),
          elderlyId,
          channel,
          recipient,
          subject:        `alert:${alert.id}:caregiver`,
          message:        careMsg,
          alertId:        alert.id.toString(),
          organizationId,
        },
      });
    }
  }

  // For CRITICAL / EMERGENCY also notify emergency contacts via SMS
  if (severity === 'CRITICAL' || alertType === 'EMERGENCY') {
    for (const ec of alert.elderly.emergencyContacts) {
      if (!ec.phone) continue;

      const ecMsg  = buildEmergencyContactMessage(alert, ec.contactName);
      const notif  = await prisma.notification.create({
        data: {
          elderlyId:      eid,
          alertId:        alert.id,
          channel:        'SMS',
          recipient:      ec.phone,
          subject:        `alert:${alert.id}:ec`,
          message:        ecMsg,
          deliveryStatus: 'PENDING',
        },
      });

      queueJobs.push({
        name: 'alert-notification',
        data: {
          notificationId: notif.id.toString(),
          elderlyId,
          channel:        'SMS',
          recipient:      ec.phone,
          subject:        `alert:${alert.id}:ec`,
          message:        ecMsg,
          alertId:        alert.id.toString(),
          organizationId,
        },
      });
    }
  }

  // ── 4. Enqueue all notifications ──────────────────────────────────────────
  const queuePriority = severity === 'CRITICAL' ? 1 : severity === 'HIGH' ? 2 : 5;

  for (const job of queueJobs) {
    await notificationQueue
      .add(job.name, job.data, { priority: queuePriority })
      .catch((err) => console.error(`[AlertService] Queue push failed for alert ${alert.id}:`, err.message));
  }

  console.log(
    `[AlertService] Alert ${alert.id} created — type: ${alertType}, severity: ${severity}, ` +
    `assignee: ${assigneeId ?? 'none'}, notifications: ${queueJobs.length}`
  );

  return alert;
}

// ── resolveAlert ──────────────────────────────────────────────────────────────

/**
 * Mark an alert RESOLVED.
 * Caller must verify organization ownership before calling this.
 */
async function resolveAlert(alertId, resolvedByUserId) {
  return prisma.alert.update({
    where: { id: BigInt(alertId) },
    data: {
      status:     'RESOLVED',
      resolvedBy: BigInt(resolvedByUserId),
      resolvedAt: new Date(),
    },
  });
}

// ── Message builders ──────────────────────────────────────────────────────────

function elderlyFullName(elderly) {
  return [elderly.firstName, elderly.lastName].filter(Boolean).join(' ') || 'ผู้สูงอายุ';
}

function buildAlertMessage(alert) {
  const name     = elderlyFullName(alert.elderly);
  const severity = alert.severity === 'CRITICAL' ? '🚨 วิกฤต' :
                   alert.severity === 'HIGH'     ? '⚠️ สูง'   :
                   alert.severity === 'MEDIUM'   ? '🔶 ปานกลาง' : '🔵 ต่ำ';
  const lines = [
    `${severity} | แจ้งเตือน: ${name}`,
    alert.title,
  ];
  if (alert.description) lines.push(alert.description);
  lines.push('กรุณาติดตามดูแลทันที');
  return lines.join('\n');
}

function buildCaregiverMessage(alert, caregiverName) {
  const name  = elderlyFullName(alert.elderly);
  const salut = caregiverName ? `คุณ${caregiverName}` : 'ท่าน';
  return (
    `เรียน ${salut}\n` +
    `ระบบแจ้งเตือนจากเทศบาล/อบต.\n` +
    `${alert.title} (${name})\n` +
    (alert.description ? `${alert.description}\n` : '') +
    `กรุณาติดต่อผู้สูงอายุหรือเจ้าหน้าที่`
  );
}

function buildEmergencyContactMessage(alert, contactName) {
  const name  = elderlyFullName(alert.elderly);
  const salut = contactName ? `คุณ${contactName}` : 'ผู้ติดต่อฉุกเฉิน';
  return (
    `🚨 ${salut} — ฉุกเฉิน!\n` +
    `${name}: ${alert.title}\n` +
    `กรุณาติดต่อทันทีหรือโทร 1669`
  );
}

function buildRiskDescription(score, riskLevel, factors) {
  const lines = [`คะแนนความเสี่ยง: ${score}/100 (${riskLevel})`];
  if (factors.missedMedications > 0)  lines.push(`• ไม่ทานยา ${factors.missedMedications} ครั้ง (7 วัน)`);
  if (factors.missedAppointments > 0) lines.push(`• พลาดนัดหมอ ${factors.missedAppointments} ครั้ง (30 วัน)`);
  if (factors.failedCalls > 0)        lines.push(`• ไม่รับสาย ${factors.failedCalls} ครั้ง (7 วัน)`);
  if (factors.diseaseCount > 0)       lines.push(`• โรคประจำตัว ${factors.diseaseCount} โรค`);
  if (factors.sentimentScore != null && factors.sentimentScore < -0.3) {
    lines.push(`• อารมณ์/จิตใจ: เป็นลบ (${factors.sentimentScore.toFixed(2)})`);
  }
  return lines.join('\n');
}

module.exports = { createAlert, createFromRiskScore, resolveAlert };
